- hosts: localhost
  connection: localhost
  tasks:
  - name: Launch EC2
    ec2:
      instance_type: t2.micro
      image: ami-0ea3405d2d2522162
      region: eu-west-1
      count: 1
      vpc_subnet_id: subnet-7afbc432
      wait: yes
      assign_public_ip: yes